# Generated by Django 5.0.7 on 2024-07-12 01:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_question_quiz'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quiz',
            old_name='questions_count',
            new_name='time_limit',
        ),
        migrations.AlterField(
            model_name='option',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='api.question'),
        ),
        migrations.AlterField(
            model_name='option',
            name='text',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.CharField(max_length=255),
        ),
    ]
