# Generated by Django 5.0.7 on 2024-07-12 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_quiz_no_of_questions'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='no_of_questions',
            field=models.IntegerField(default=0),
        ),
    ]
